"""empty message

Revision ID: 1ca2adae0ad9
Revises: 53d5823b8e82
Create Date: 2020-05-12 21:01:12.075268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ca2adae0ad9'
down_revision = '53d5823b8e82'
branch_labels = None
depends_on = None

# NOTE!!!!!
# I chose 'users_username_key' -> we need this name, so we could downgrade, otherwise,
# the default value is None, which prevents us from downgrade


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('users_username_key', 'users', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_username_key', 'users', type_='unique')
    # ### end Alembic commands ###
