"""added email column

Revision ID: a7d445f5467c
Revises: 1ca2adae0ad9
Create Date: 2020-05-13 01:42:12.119901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7d445f5467c'
down_revision = '1ca2adae0ad9'
branch_labels = None
depends_on = None


# NOTE - 'user_email_key' -> I chose this constraint key

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=80), nullable=False))
    op.create_unique_constraint('user_email_key', 'users', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_email_key', 'users', type_='unique')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
